// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

// 构建 PostgreSQL 连接 URL
function getDatabaseUrl(): string {
  // 优先使用 DATABASE_URL
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }
  
  // 从 PG* 环境变量构建 URL（用于 AWS RDS）
  const host = process.env.PGHOST;
  const port = process.env.PGPORT || "5432";
  const user = process.env.PGUSER;
  const password = process.env.PGPASSWORD;
  const database = process.env.PGDATABASE || "postgres";
  const sslMode = process.env.PGSSLMODE;
  
  if (host && user && password) {
    let url = `postgresql://${user}:${encodeURIComponent(password)}@${host}:${port}/${database}`;
    if (sslMode) {
      url += `?sslmode=${sslMode}`;
    }
    return url;
  }
  
  // 返回一个占位符 URL，用于 prisma generate（不需要真正连接）
  // prisma generate 只需要 schema，不需要数据库连接
  return "postgresql://placeholder:placeholder@localhost:5432/placeholder";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
